name: Matrix Strategy Include Sample
on: push
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest,windows-latest,]
        node: [12, 14, 16]
        include:
          - os: windows-latest
            node: 16
            npm: 8
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - if: ${{ matrix.npm }}
        run: npm install -g npm@${{ matrix.npm }}
      - run: npm --version