version: '3'
services:
  database:
    image: docker.io/bitnami/mongodb:latest
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

  api:
    depends_on:
      - database
    build:
      target: python
      context: .
    environment:
      - MONGO_URI=mongodb://database:27017
    command: uvicorn routes:app --host 0.0.0.0
    ports:
    - "8000:8000"

volumes:
  mongodb_data:
    driver: local